Imported Debian patch 4.3.24-0vanir1

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,8 +1,8 @@
 #!/bin/sh
 set -e
 
-version=4.3.4
-hash=f92d187a84bfed22635fc2d6167c5c42
+version=4.3.24
+hash=c6b61774e323b70da0d4f5677ef56f1c53990eccef859d3c720d814f98a01f8d
 file=Oracle_VM_VirtualBox_Extension_Pack-$version.vbox-extpack
 
 error ()
@@ -16,7 +16,7 @@ if [ "$1" = "configure" ] ; then
 	cd /usr/share/virtualbox-ext-pack
 	echo "virtualbox-ext-pack: downloading: http://download.virtualbox.org/virtualbox/$version/$file"
 	wget -q -N http://download.virtualbox.org/virtualbox/$version/$file
-	echo "$hash  $file" | md5sum -c > /dev/null 2>&1 || error
+	echo "$hash  $file" | sha256sum -c > /dev/null 2>&1 || error
 	vboxmanage extpack install --replace $file
 fi
 
