Revert, §2

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,12 +1,26 @@
 #!/bin/sh
 set -e
 
+version=5.1.4
+hash=9462ff1b567c37ad9a33c0c7ca1925776615ec89b5a72563f29a8cc8514cf316
+file=Oracle_VM_VirtualBox_Extension_Pack-$version.vbox-extpack
+
+error ()
+{
+	echo "Hash mismatch $file"
+	exit 1
+}
+
 # Source debconf library.
 . /usr/share/debconf/confmodule
 
 if [ "$1" = "configure" ] ; then
 	cd /usr/share/virtualbox-ext-pack
-	vboxmanage extpack install --replace Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack
+	echo "virtualbox-ext-pack: downloading: http://download.virtualbox.org/virtualbox/$version/$file"
+	echo "The file will be downloaded into /usr/share/virtualbox-ext-pack"
+	wget -q -N http://download.virtualbox.org/virtualbox/$version/$file
+	echo "$hash  $file" | sha256sum -c > /dev/null 2>&1 || error
+	vboxmanage extpack install --replace $file
 fi
 
 #DEBHELPER#
