Move the license check to the preinstall script.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -15,17 +15,12 @@ error ()
 . /usr/share/debconf/confmodule
 
 if [ "$1" = "configure" ] ; then
-        db_get virtualbox-ext-pack/license
-        if [ "$RET" = true ] ; then
-		cd /usr/share/virtualbox-ext-pack
-		echo "virtualbox-ext-pack: downloading: http://download.virtualbox.org/virtualbox/$version/$file"
-		echo "The file will be downloaded into /usr/share/virtualbox-ext-pack"
-		wget -q -N http://download.virtualbox.org/virtualbox/$version/$file
-		echo "$hash  $file" | sha256sum -c > /dev/null 2>&1 || error
-		vboxmanage extpack install --replace $file
-	else
-		exit 1
-	fi
+	cd /usr/share/virtualbox-ext-pack
+	echo "virtualbox-ext-pack: downloading: http://download.virtualbox.org/virtualbox/$version/$file"
+	echo "The file will be downloaded into /usr/share/virtualbox-ext-pack"
+	wget -q -N http://download.virtualbox.org/virtualbox/$version/$file
+	echo "$hash  $file" | sha256sum -c > /dev/null 2>&1 || error
+	vboxmanage extpack install --replace $file
 fi
 
 #DEBHELPER#
