Update error codes for the ext pack installation, distinguish download failures and installation failures

diff --git a/debian/postinst.in b/debian/postinst.in
--- a/debian/postinst.in
+++ b/debian/postinst.in
@@ -8,8 +8,12 @@ accept_license=56be48f923303c8cababb0bb4c478284b688ed23f16d775d729b89a2e8e5f9eb
 
 error ()
 {
-	echo "Hash mismatch $file: expected $hash, or wrong accept-license key, removing the file."
-	rm -f /usr/share/virtualbox-ext-pack/$file
+	if [ "$1" = "hash" ] ; then
+		echo "Hash mismatch $file: expected $hash, removing the file."
+		rm -f /usr/share/virtualbox-ext-pack/$file
+	elif [ "$1" = "install" ]; then
+		echo "Installation error: License key incorrect or unknown problem during installation."
+	fi
 	exit 1
 }
 
@@ -17,15 +21,14 @@ error ()
 . /usr/share/debconf/confmodule
 
 if [ "$1" = "configure" ] ; then
-	echo "removing old virtualbox extension packs"
 	rm -f /usr/share/virtualbox-ext-pack/Oracle_VM_VirtualBox_Extension_Pack-*.vbox-extpack
 	cd /usr/share/virtualbox-ext-pack
-	echo "virtualbox-ext-pack: downloading: https://download.virtualbox.org/virtualbox/$version/$file"
+	echo "virtualbox-ext-pack: downloading: http://download.virtualbox.org/virtualbox/$version/$file"
 	echo "The file will be downloaded into /usr/share/virtualbox-ext-pack"
 	/usr/bin/wget -q -N http://download.virtualbox.org/virtualbox/$version/$file
-	echo "$hash  $file" | sha256sum -c > /dev/null 2>&1 || error
-	vboxmanage extpack install --replace --accept-license=$accept_license $file || error
-	#rm -f /usr/share/virtualbox-ext-pack/$file
+	echo "$hash  $file" | sha256sum -c > /dev/null 2>&1 || error hash
+	vboxmanage extpack install --replace --accept-license=$accept_license $file || error install
+	rm -f /usr/share/virtualbox-ext-pack/$file
 fi
 
 #DEBHELPER#
